### ISSUE TITLE
[Pathfinder v2.0.11] Constant errors in log in BogWitch update

### ISSUE THREAD

**Issue by Maoman1** [CrystalFerrai/ValheimMods#38] opened 2024-10-31 08:00 UTC
This error just spams constantly the entire time while playing.

```[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Pathfinder.PathfinderPlugin+Minimap_Patches.GetExploreRadius (Player player) (at <e8c2a428bebd40e09f977817bf59430b>:0)
(wrapper dynamic-method) Minimap.DMD<Minimap::UpdateExplore>(Minimap,single,Player)
Minimap.Update () (at <94a8ab08dca748d3beb540d5228ac7b0>:0)```

**Comment by Schorsch0815** [comment] 2024-10-31 21:32
I did not check the console but within the game the map is no longer updated. Let's say uncovered map will stay uncovered.

**Comment by CrystalFerrai** [comment] 2024-11-05 18:24
Thank you for the report. I am currently busy with other things and do not have time to update Valheim mods. I will look into all reported issues the next time I get a chance, hopefully within a few weeks.

**Comment by Maoman1** [comment] 2024-11-14 01:01
I got it working again if you wanna update this one at least. Here's the new .dll. It was the GetExploreRadius method that was the problem.
https://mega.nz/file/hI9GQBZa#hzpcJF4Lj1l80MpICK4ewB0W-ad3jb4qYuLgcOZ-F5M

**Comment by CrystalFerrai** [comment] 2024-11-16 00:31
Version 2.0.12 has been released with a fix for this issue

**Closed by CrystalFerrai** 2024-11-16 00:31 UTC

**Comment by Maoman1** [comment] 2024-11-16 07:20
Out of curiosity, did you use my code at all or did you just ignore mine and fix it yourself? (I won't be offended I'm just wondering)

**Comment by CrystalFerrai** [comment] 2024-11-16 18:00
I did not look at your code. I just went through my normal process of updating mods where I update game DLLs, build and fix errors, run the game and fix exception, then do some general functionality testing. I appreciate issue reports in case there is something extra I should test. In this case, I did some extra testing around explore radius while on a boat since you mentioned an issue with it. But I was not able to reproduce that issue after fixing the exception.

**Comment by Maoman1** [comment] 2024-11-18 22:43
Huh... I am still having an issue with the explore radius on ship being absolutely massive. Here is a screenshot of my map, with some (probably unnecessary) highlighting to show where I traveled and what got explored. Surely this is not normal, right? I tried reinstalling the mod and deleting the config file so there shouldn't be anything left of the changes I made while messing around, but it made no difference.
![1ICq4debsB](https://github.com/user-attachments/assets/dce45c6e-6c70-48d5-829a-e3db6ab8b912)

**Comment by CrystalFerrai** [comment] 2024-11-20 02:59
Since I am not able to reproduce the issue (nor a few other people i know), my best guess is that you have some other mod that is interacting with Pathfinder in some way. I recommend testing with other mods disabled to see what happens.
